KAR-490 | add service type to next version flow
allegro-actions/next-version pull request #1
Opened 2021-07-15 10:50 UTC by dkubicki

2021-07-15 16:32 UTC, bgalek requested changes

2021-07-15 16:32 UTC, bgalek commented on .gitignore
> +.idea
this should be in your os :) there is an instruction on askbartosz

2021-07-15 16:32 UTC, bgalek commented on action.js
> +const { parseLibraryTag, parseServiceTag } = require('./tag-parser');
what do you think about leaving only parse() interface, with additional parameter tagType?

2021-07-15 16:32 UTC, bgalek commented on action.js
> +        console.log('TUTAJJJJJ PREFIX' + 'TUTAJJJJJ VERSION' + prefix, version)
remove ;)

2021-07-15 16:32 UTC, bgalek commented on action.js
> +      return `1${mainBranch ? '' : '-SNAPSHOT'}`;
I would add v1 as a default, tags are string so we should not encourage people to use them like integers

2021-07-15 16:32 UTC, bgalek commented on incrementer.js
> +            return prefix + ++version + suffix
template string would be better i think ;) but that's up to you

2021-07-15 17:05 UTC, bgalek commented
I was talking to Piotr Betkier, and he pointed out an important thing. 
I think we should not imply any convention regards to type of code teams are developing.

Let's change type: service/library to:
- semver 
- custom (your new implementation)
- legacy? (I mean old allegro style with prefix ;))

2021-07-16 06:39 UTC, dkubicki commented on .gitignore
> +.idea
Set global .gitignore :)

2021-07-16 07:00 UTC, dkubicki commented on action.js
> +const { parseLibraryTag, parseServiceTag } = require('./tag-parser');
yeap, It was my first thought ;)

2021-07-16 07:02 UTC, dkubicki commented on action.js
> +      return `1${mainBranch ? '' : '-SNAPSHOT'}`;
indeed, 58L

2021-07-16 10:26 UTC, closed without merging